# Generated by Django 4.1.1 on 2022-10-08 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_alter_tool_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='user',
        ),
    ]
